version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kyxquota-bun
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # 服务器配置
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      
      # OAuth2 配置（必须设置）
      - LINUX_DO_CLIENT_ID=${LINUX_DO_CLIENT_ID}
      - LINUX_DO_CLIENT_SECRET=${LINUX_DO_CLIENT_SECRET}
      - LINUX_DO_REDIRECT_URI=${LINUX_DO_REDIRECT_URI}
      
      # 管理员密码
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      
      # 数据库路径
      - DATABASE_PATH=/app/data/kyxquota.db
    volumes:
      # 数据持久化
      - ./data:/app/data
      # 日志持久化（可选）
      - ./logs:/app/logs
    networks:
      - kyxquota-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  kyxquota-network:
    driver: bridge

volumes:
  data:
    driver: local

